run:
  deadline: 7m
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - depguard
    - godot
    - goimports
    - revive
    - whitespace

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: github.com/pkg/errors
            desc: 'Use errors or fmt instead of github.com/pkg/errors'
  errcheck:
  goimports:
    local-prefixes: github.com/stealthrocket/wzprof
  misspell:
    locale: US
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
      - name: unexported-return
        severity: warning
        disabled: true
