project_name: wzprof
dist: ./goreleaser/dist

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wzprof/main.go
    binary: wzprof
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}

release:
  github:
    owner: stealthrocket
    name: wzprof
  draft: true
  prerelease: auto
  mode: replace
changelog:
  use: github-native
