repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        name: Insert license in comments (Go)
        args:
          - --license-filepath=scripts/LICENSE.txt
          - --comment-style=//
          - --use-current-year
          - --fuzzy-match-generates-todo
        exclude: _test.go$
        types: [go]
