name: build
on:
  push:
    tags:
      - v*
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  # renovate: datasource=go depName=github.com/golangci/golangci-lint
  GOLANGCI_LINT_VERSION: v1.60

jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling of Go files
      uses: crate-ci/typos@master
      with:
        files: '*.go'
        write_changes: true

  golangci-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 5m

  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: .go-version
        check-latest: true

    - name: Setup python
      run: make python

    - name: Test
      run: go test ./...
